[package]
name = "neat-template-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
tokio = { version = "1.9.0", features = ["full"] }
